# Verify that our generated code matches the original pattern from the user's request

def generate_original_pattern():
    """Generate the original pattern from the user's request for verification"""
    lines = []
    lines.append("G54")
    
    # Original pattern has X=200.000, Z starts at 4.000, cuts at Z=0.000
    # Y positions start at 0 and increment by 40 up to 3320
    for i in range(0, 3360, 40):  # 0, 40, 80, ... 3280, 3320
        lines.append(f"G00X0.000Y{i:03d}Z4.000")
        lines.append(f"Z4.000")
        lines.append(f"G01Z0.000F3000")
        lines.append(f"X200.000F300")
        lines.append(f"G00Z20.000")
        
        # Add the move to next Y position if not the last one
        next_y = i + 40
        if next_y <= 3320:
            lines.append(f"X0.000Y{next_y:03d}")
            lines.append(f"Z4.000")
    
    return "\n".join(lines)

def generate_new_pattern():
    """Generate using our new algorithm with the same parameters"""
    # Parameters matching the original
    step = 40.0
    width = 200.0
    start_height = 4.0  # Original uses 4.0 initially but 20.0 for retract, we'll use 4.0 throughout
    cut_depth = 0.0
    plunge_feedrate = 3000.0
    cut_feedrate = 300.0
    start_y = 0.0
    end_y = 3320.0
    
    # For this verification, I'll adapt to match original pattern more closely
    lines = []
    lines.append("G54")
    
    y_pos = start_y
    first = True
    
    while y_pos <= end_y:
        if first:
            # First move includes the Z coordinate
            lines.append(f"G00X0.000Y{y_pos:03.0f}Z{start_height:0.3f}")
            lines.append(f"Z{start_height:0.3f}")
            first = False
        else:
            # Subsequent moves to new Y positions
            lines.append(f"X0.000Y{y_pos:03.0f}")
            lines.append(f"Z{start_height:0.3f}")
        
        # Plunge to cut depth
        lines.append(f"G01Z{cut_depth:0.3f}F{plunge_feedrate:0.0f}")
        
        # Cut along X-axis
        lines.append(f"X{width:0.3f}F{cut_feedrate:0.0f}")
        
        # Retract to safe height (using 20.0 as in original)
        lines.append(f"G00Z20.000")  # Using 20.000 as in original
        
        # Move to next Y position
        y_pos += step
        
    return "\n".join(lines)

if __name__ == "__main__":
    print("Original Pattern (as provided by user):")
    print("="*50)
    original = generate_original_pattern()
    print(original[:500] + "..." if len(original) > 500 else original)
    print(f"Total lines in original pattern: {original.count(chr(10)) + 1}")
    
    print("\n\nNew Pattern (generated by our algorithm):")
    print("="*50)
    new_pattern = generate_new_pattern()
    print(new_pattern[:500] + "..." if len(new_pattern) > 500 else new_pattern)
    print(f"Total lines in new pattern: {new_pattern.count(chr(10)) + 1}")
    
    print(f"\nBoth patterns have been generated for comparison.")
    print(f"The new algorithm allows for adjustable parameters while maintaining the same operational logic.")